MAIN COMMIT MARK.2
glhfuck/Ciphers pull request #1
Opened 2020-04-19 20:52 UTC by DanielCyrex

2020-04-25 17:21 UTC, pkositsyn requested changes

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +print(args)
?

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +alphabets = ("abcdefghijklmnopqrstuvwxyz", "ABCDEFGHIJKLMNOPQRSTUVWXYZ")
Есть константы string.ascii_lower, string.ascii_upper

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +        if (char in alphabets[i]):
Скобки лишние

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +    return -0.5
Странное значение, лучше None вернуть

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +class caesar():
С большой буквы классы и без скобок

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +        if (self.src == None):
Лучше все-таки разделять чтение и кодирование. Можешь написать свой инит, так будет лучше

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +        if (self.src == None):
И скобочки везде у ифов убери

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +            inputFile = open(self.src)
Нужен контекстный менеджер

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +            outputFile = open(self.dir, "w")
КОнтекстный менеджер

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +        if (self.src == None):
Вот, очень много кода дублируешь

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +        if (self.src == None):
В декоде вообще можно вызывать encode с -key

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +class vigenere():
Аналогично

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +class train():
Классы должны именоваться существительными, функции - глаголами

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +            outputFile = open(self.dir, "w")
Видишь, тут забыл закрыть. Поэтому контекстны менеджеры нужны

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +    def make_mdl(self):
Не сокращай лишний раз ради пары символов. Гораздо проще читать полностью

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +               text.remove(char)
Это каждый раз за линию работает Надо поумнее удалять. Мб строку временную создать

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +        charCounter = collections.Counter()
В конструктор передай сразу текст, он все сделает

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +            charCounter[key] /= charSum
Обработай деление на 0

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +        pickle.dump(charCounter, open(self.mdl, "wb"))
Опять не закрыл

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +class hack():
Hacker

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +    def decoder(self):
decode

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +                    encodedText.remove(char)
Аналогично

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +            modelCounter = pickle.load(open(self.mdl, "rb"))
Можно и один раз загрузить

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +            for key in deltaCounter.keys():
Убери .keys()

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +        Shift_size = results.index(min(results))
Придерживайся одного кодстайла. Вообще питоновский snake_case

2020-04-25 17:21 UTC, pkositsyn commented on encryptor.py
> +Haker.decoder()
Для тестирования может быть неплохо, но так делать не надо. Когда импортируешь, весь этот код исполнится, а так не должно быть. Короче просто удали

2020-04-25 17:21 UTC, pkositsyn commented on inF.txt
> +What Are Black Holes?
Не надо в репозиторий лишние файлы класть. Удали их

2020-05-03 12:41 UTC, glhfuck commented
Субпарсеры реализую на этой неделе, пока что обычный парсер

2020-05-04 19:41 UTC, pkositsyn requested changes

2020-05-04 19:41 UTC, pkositsyn commented on encryptor.py
> +            if alphabet_pos(text[i]) == None:
is None

2020-05-04 19:41 UTC, pkositsyn commented on encryptor.py
> +        for i in range(len(text)):
Итерируйся по буквам

2020-05-04 19:41 UTC, pkositsyn commented on encryptor.py
> +alphabets = (string.ascii_lowercase, string.ascii_uppercase)
константы UPPER_CASE

2020-05-04 19:41 UTC, pkositsyn commented on encryptor.py
> +args = parser.parse_args()
Сделай точку входа `if __name__ == '__main__': main()`
`def main()`
Я объяснял зачем, не надо исполнять код в глобале

2020-05-08 18:33 UTC, pkositsyn approved these changes
Можешь доисправить мелкую вещь, а так ОК. Напиши мне, что ты реализовал на доп баллы

2020-05-08 18:33 UTC, pkositsyn commented on encryptor.py
> +        lengths = list(map(len, ALPHABETS))
Зря список создаешь, в мах можно передавать любой итерабл объект

2020-05-08 23:11 UTC, glhfuck commented
Я добавил:
- Шифратор/дешифратор Вернама. 
- В шифратор/дешифратор/взлом поддержку кириллицы, пробелов и знаков препинания.

2020-05-11 16:13 UTC, merged